### ISSUE TITLE
Unnumbered Sections

### ISSUE THREAD

**Issue by johannesbottcher** [ntd/tccv#1]
Hi Nicola, 

a question came up on [TeX.Stackexchange](http://tex.stackexchange.com/q/223607/37907) [1] where a user used the classical bibliography setup to get his references into the CV. As the default is a starred section, the result is not satisfying. One can get around this by using a _numbered section_, as shown in the answer i gave myself. 

I am not sure if you want to address the issue.

Best regards
Johannes Böttcher

[1] http://tex.stackexchange.com/questions/223607/does-the-bibliography-command-specify-a-section-anywhere

**Comment by ntd** [comment]
Hi Johannes,

thanks for letting me know. Are you willing to provide a suggestion in a pull-request form?

It could break backward compatibility if needed. I'm using this class for ten or so private resumes, so updating all of them is not a big issue.

**Comment by johannesbottcher** [comment]
I would simply use the `\KOMAoption{bibliography}{totocnumbered}` as in the answer i gave at TeX.SX. If a user decides to have a bibliography, he won't see any difference as nothing is numbered anyway. But internally, a `section` (rather than `section*`) is used.  This will even work for `biblatex` as it processes the keywords.

**Comment by ntd** [comment]
Well, pull requests make things such as credits and contributions identification a lot more clear.

If you are not interested I'll reference your help in the commit message, like in the good ol' days.

**Comment by ntd** [comment]
Thanks for your pull request #2: merged. I reverted fausto.en.tex that I think you used as test bed.

**Comment by johannesbottcher** [comment]
Partly sandbox, partly using `fontsize=8pt` to not get into compatibility mode of KOMA (see warning in the log).

**Comment by ntd** [comment]
Life's too short for reading LaTeX logs.

Thanks for the report: I addressed this issue in commit 3aa68ece1a267c7a92fda409ce97e2534d701c7c.
