### ISSUE TITLE
A bug when adding bullet points

### ISSUE THREAD

**Issue by vwxyzjn** [ntd/tccv#5]
Hi,

I am trying to add bullet point to the file, but then the pdf looks like this:

![image](https://user-images.githubusercontent.com/5555347/34970635-79269116-fa43-11e7-995c-e484ec620033.png)

The related code is:

```tex
\begin{eventlist}

\item{July 2007 -- Present}
     {Furman University, Greenville, SC}
     {Software Developer}

Development and testing of automatic and semiautomatic machines for
ribbon winding on spools and rolls (safety belts, hook-and-loop tapes,
elastic ribbon and bindings). Designing of electrical schematics on
2D cad and user manuals drafting.

\begin{itemize}
\item This is the first entry in our list
\end{itemize}
```

How could I fix it? Thank you.

**Comment by ntd** [comment]
This is because I redefine `item` inside the `eventlist` environment. It should error out when compiling though.

A way to address this issue is to define your bullet list outside of `eventlist`, e.g.:

```tex

\newbox\mybulletlist
\setbox\mybulletlist\vbox{%
    \begin{itemize}
        \item This is the first entry in our list
    \end{itemize}%
}

\begin{eventlist}

\item{July 2007 -- Present}
     {Furman University, Greenville, SC}
     {Software Developer}

Development and testing of automatic and semiautomatic machines for
ribbon winding on spools and rolls (safety belts, hook-and-loop tapes,
elastic ribbon and bindings). Designing of electrical schematics on
2D cad and user manuals drafting.

\use\mybulletlist
```
Maybe there are more elegant solutions but, as you can guess from some tccv implementation choices, I am not that good in LaTeX development.

Let me know if this solves your problem: if that is the case, I'll add a note to the README.

**Comment by vwxyzjn** [comment]
@ntd Hi,

Thank you for the quick response. I basically change the code to 

```tex
\newenvironment{eventlist}{%
    \newcommand*\inskip{}
    \newcommand\event[3]{%
	\inskip%
	{\raggedleft\textsc{##1}\\[1pt]}
	\ifstrempty{##2}{}{##2\\[2pt]}
	{\Large\textit{##3}}
	\medskip
	\renewcommand\inskip{\bigskip}}}
    {\bigskip}
```

So that I can use 

```tex
\begin{eventlist}

\event{July 2007 -- Present}
     {Furman University, Greenville, SC}
     {Software Developer}

\begin{itemize}
    \item test
\end{itemize}
```

It's kind of elegant, but this modification will break existing code.

**Comment by vwxyzjn** [comment]
@ntd Would you consider creating a new subcommand for each xxx-list? In that way, you would not overwrite the default ``\item`` command.  Currently, my pdf looks like this, with some adjustments made to the style to ``itemize`` environment:

[Two_column_CV (2).pdf](https://github.com/ntd/tccv/files/1637299/Two_column_CV.2.pdf)

**Comment by ntd** [comment]
@vwxyzjn no, I want to retain backward compatibility.

Feel free to fork and experiment though: I don't have any objection with that.
