### ISSUE TITLE
Allow the personal box to have an arbitrary amount of items

### ISSUE THREAD

**Issue by lenormf** [ntd/tccv#8]
Hi,

Would it be possible to allow the `\personal` box to have an arbitrary amount of entries? I currently have to customize the class manually, it's a bit cumbersome.

Something like:

```
\personal{\SYMBOL{…}}{item}…
```

Thanks!

**Comment by ntd** [comment]
I'll check if I can provide such an environment while retaining backward compatibility.

**Comment by lenormf** [comment]
Well the usage example I gave would clearly break backward compatibility. But I think it's worth it.

**Comment by ntd** [comment]
> Well the usage example I gave would clearly break backward compatibility

This is why I'll need to check: I'll never break backward compatibility. I was thinking more along the lines of providing a new environment and deriving `\personal` from it.

**Comment by ntd** [comment]
I just added the `keyvaluelist` environment: in the commit description I provided a basic example of use. The `\personal` command is now based on it, so it is another (more complex) use case you can examine.

**Comment by lenormf** [comment]
Thanks!
